### ISSUE TITLE
Install is failed with node.js version 17.2.0 (but successful with 13.10.1)

### ISSUE THREAD

**Issue by YugoHino** [kintone-labs/kintone-cli#45]
If possible, please write the issue and pull-request in English.
But it's not an absolute rule. Japanese is ok.

## Version

- kintone-cli v0.2.1

## Environment

- Operating System: Docker on Windows (Docker desktop for Windows)
- Browser: - 
- Node.js version: v17.2.0

## Current Behavior

`npm install -g git://github.com/kintone-labs/kintone-cli.git` is not working on node.js version 17.2.0. 
When I use following dockerfile that this node.js version is 13.10.1, above command is working and install is successfully done. `kintone-cli` command works on terminal in docker. 
```
FROM node:13.10.1

WORKDIR /app/test_app
# proxy
ENV http_proxy http://<company proxy>:8080
ENV https_proxy http://<company proxy>:8080
RUN npm -g config set proxy http://<company proxy>:8080
RUN npm -g config set https-proxy http://<company proxy>:8080
RUN npm -g config set registry "http://registry.npmjs.org/"

RUN apt-get -y update \
    && apt-get -y install sudo \ 
    && npm install -g npm

RUN npm -g install git://github.com/kintone-labs/kintone-cli.git
```

However, just chage it to later version such like 17.2.0, install is failed with following error. 
```
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/internal/operators/windowToggle.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operator/windowToggle.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operators/windowToggle.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/add/operator/windowWhen.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/internal/operators/windowWhen.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operator/windowWhen.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operators/windowWhen.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/add/operator/windowWhen.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/internal/operators/windowWhen.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operator/windowWhen.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operators/windowWhen.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/add/operator/withLatestFrom.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/internal/operators/withLatestFrom.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operator/withLatestFrom.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operators/withLatestFrom.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/add/operator/withLatestFrom.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/internal/operators/withLatestFrom.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operator/withLatestFrom.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operators/withLatestFrom.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/add/observable/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/add/operator/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/internal/observable/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/internal/operators/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/observable/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operator/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operators/zip.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/add/observable/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/add/operator/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/internal/observable/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/internal/operators/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/observable/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operator/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operators/zip.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/add/operator/zipAll.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/internal/operators/zipAll.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operator/zipAll.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/operators/zipAll.d.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/add/operator/zipAll.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/internal/operators/zipAll.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operator/zipAll.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/operators/zipAll.ts'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/_esm2015/LICENSE.txt'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/_esm5/LICENSE.txt'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/LICENSE.txt'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/usr/local/lib/node_modules/kintone-cli/node_modules/rxjs/src/LICENSE.txt'
``` 

Does anyone successfully install kintone-cli on node.js later version? 

## Expected Behavior

Successfully installed on node.js version 17.2.0

**Comment by TomokoMiyake** [comment]
@YugoHino 
Thank you for the issue registration.
Could you confirm the behavior if you have already tried it?
- Do you succeed in installation when you use the LTS (recommended) version of Node.js (v16.13.1) in the dockerfile?
  https://nodejs.org/ja/download/
- Do you succeed in installation when you use Node.js v17.2.0 and the previous version of kintone-cli?

**Comment by YugoHino** [comment]
@TomokoMiyake 
Thank you for the quick responce. 

1. Node.js v16.13.1 version try
I haven't tried it and I did it now. But this looks same result as 17.2.0. I will try to find out which version is latest for working between 13.10.1 and 16.13.1. 

2. Success version of kintone-cli on 17.2.0
I think I tried v0.1.6 because I tried it few months ago and it was not working.

**Comment by YugoHino** [comment]
According to my check, latest version which is working is 14.18.2(last version of 14). 15.0.0 and later version responses any errors to install kintone-cli. 

My check results
13.10.1 success
13.11.0 success
14.7.0 success
14.18.2 success
15.0.0 failed with error pattern 1
15.5.1 failed with error pattern 2
15.14.0 failed with error pattern 2
16.13.1 failed with error pattern 2
17.2.0 failed with error pattern 2

Only 15.0.0 has different error pattern. Which is following error. But I think this error is only this 15.0.0 version.
```
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-03T07_38_24_067Z-debug.log

```

**Comment by YugoHino** [comment]
I also checked and figured out as following.

node.js version = 14.18.2

npm version
default(6.14.15)  successed
7.0.2 failed with pattern 2
7.0.3 failed with pattern 2
7.3.0 failed with pattern 2

So, those error might be caused by npm version 7.0.2 and later.

**Comment by TomokoMiyake** [comment]
@YugoHino 
Thank you very much for the detailed information!
I also encountered the issue using the Node.js version after 14.18.2.
We will investigate the cause of it.

**Comment by TomokoMiyake** [comment]
@YugoHino 
Sorry, I commented before you posted https://github.com/kintone-labs/kintone-cli/issues/45#issuecomment-985309297.

Yes, I also suspected the npm support status of the installation way.
But I found the description in the official reference.
> https://docs.npmjs.com/cli/v8/commands/npm-install#description
> npm install git://github.com/npm/cli.git#v1.0.27

We will investigate more and reach out to you.

**Comment by YugoHino** [comment]
Thank you @TomokoMiyake 

As a temporally solution, I install npm@6.14.5 before installing kintone-cli. After that, I install npm later version. 

``` Dockerfile
RUN npm install -g npm@6.14.5
RUN npm -g install https://github.com/kintone-labs/kintone-cli.git
RUN npm install -g npm
```

**Comment by TomokoMiyake** [comment]
@YugoHino 
Thank you for considering the solution.
We will let you know when we find the cause and can fix it.
Sorry for the inconvenience for a while.

**Comment by TomokoMiyake** [comment]
@YugoHino 
We wanna try to fix it, but we don't have much time to work on it within December.
I will let you know soon when we solve this issue.

Thank you!

**Comment by TomokoMiyake** [comment]
@YugoHino 
We have investigated in detail. Please check below.

- This problem seems to be occurred by the npm bug with the node version 15.0.0 and after it when installing globally using `git://xxx.git` way.
  This does not occur when installing locally like `npm install git://github.com/kintone-labs/kintone-cli.git`.
  We found the same issue here.
  https://githubmemory.com/repo/npm/cli/issues/3910
- We will suggest the two options as follows:
  [Option 1]: use `yarn` for installing this package on all node version
  [Option 2]:
  - use `yarn` for installing this package on node version >= 15.0.0
  - use `npm` or `yarn` for installing this package on node version < 15.0.0

*Note that when you use `yarn`, please use this command.
 `yarn global add git://github.com/kintone-labs/kintone-cli.git`

**Comment by YugoHino** [comment]
@TomokoMiyake 
Thank you so much. Now it's working with using yarn in my environment as well. 
node v16.13.1
npm 8.3.0

Hope if those command options to install will be noted in readme file on this repogitory. 

That's ok to close this ticket for me.

**Comment by TomokoMiyake** [comment]
@YugoHino 
Thank you for checking and trying again.
I am relieved it's working in your environment.

> Hope if those command options to install will be noted in readme file on this repogitory.

I will add `yarn global add git://github.com/kintone-labs/kintone-cli.git` to README.
Thanks for the suggestion.

**Comment by TomokoMiyake** [comment]
@YugoHino 
I have merged the README update to the master.
https://github.com/kintone-labs/kintone-cli/pull/46

Thank you, again.
