### ISSUE TITLE
Cannot install CLI globally

### ISSUE THREAD

**Issue by y-maeda-wv** [kintone-labs/kintone-cli#49]
kintone CLI を使って、カスタマイズのプロジェクトを作成したいのですが、npm install すると大量の警告がでて、正常にインストールできません。

I want to create a customization project using the kintone CLI, but when I npm install, I get a lot of warnings and cannot install it properly.

## Version

- kintone-cli v0.2.2

## Environment

- Operating System: windows 10 pro
- Node.js version: v16.13.1

## Current Behavior

```
npm install -g git://github.com/kintone-labs/kintone-cli.git

npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\rxjs\dist\cjs\internal\util\isReadableStreamLike.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\lodash\collection.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\lodash\fp\collection.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\rxjs\dist\esm\internal\util\isReadableStreamLike.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\rxjs\dist\esm5\internal\util\isReadableStreamLike.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\lodash\commit.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\rxjs\dist\cjs\internal\util\isScheduler.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\lodash\fp\commit.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\rxjs\dist\esm\internal\util\isScheduler.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open 'C:\Users\xx\AppData\Roaming\npm\node_modules\kintone-cli\node_modules\lodash\compact.js'
```

**Comment by TomokoMiyake** [comment]
@y-maeda-wv 
Thank you for the feedback.
We got the same issue here and found that it is the npm side issue.
This problem seems to be occurred by the npm bug with the node version 15.0.0 and after it when installing globally using `git://xxx.git` way.
https://github.com/kintone-labs/kintone-cli/issues/45#issuecomment-993133410

If you want to use Node.js v16, please install kintone-cli globally by `yarn` instead.
We added the `yarn` installation way at README, too.

**Comment by y-maeda-wv** [comment]
@TomokoMiyake 
Thanks for the reply.
I'll try it with yarn.

Doesn't this project publish to npm?

-----
返信ありがとうございます。
yarn で試してみます。

このプロジェクトは npm にパブリッシュしないのですか？

**Comment by TomokoMiyake** [comment]
@y-maeda-wv 
> Doesn't this project publish to npm?

We have a possibility to publish kintone-cli to the npmjs in near future. I think it will be useful for the developers.
Thanks for asking!

**Comment by y-maeda-wv** [comment]
I understand. Thank you very much.
-----
分かりました。ありがとうございます。
